#!/bin/sh

_os=`uname -s`
_arch=`uname -m`

gen_link_flags() {
   case $_os in
      FreeBSD)
	     echo "-lutil"
             ;;
      *)
             echo
             ;;
   esac
        
}

gen_compile_flags() {
   echo " -DORDER -I. -DDEBUG=0 -DOS_NAME=$_os -DARCH_NAME=$_arch "
}

case $1 in
link)
    gen_link_flags
    ;;
compile)
    gen_compile_flags
    ;;
esac
